[env]
TERM = "xterm-256color"

[colors.primary]
foreground = "#2b303b"
background = "#ededed"

[font]
size = 9.0

[font.bold]
family = "jetbrains mono"
style = "Bold"

[font.bold_italic]
family = "jetbrains mono"
style = "Bold Italic"

[font.italic]
family = "jetbrains mono"
style = "Italic"

[font.normal]
family = "jetbrains mono"
style = "Regular"

[window]
padding = { x = 15, y = 15 }
opacity = 1
title = "Alacritty"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "Always"
